-- BUILD ONLY: run npm run db:migrate when Oracle available

CREATE TABLE ROLES (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME       VARCHAR2(100) UNIQUE NOT NULL,
  PERMISSIONS CLOB CHECK (PERMISSIONS IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE USERS (
  ID           RAW(16)       DEFAULT SYS_GUID() PRIMARY KEY,
  KEYCLOAK_ID  VARCHAR2(255) UNIQUE NOT NULL,
  EMAIL        VARCHAR2(255) UNIQUE NOT NULL,
  NAME         VARCHAR2(255) NOT NULL,
  ROLE_ID      NUMBER        REFERENCES ROLES(ID),
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  DELETED_AT   TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IDX_USERS_KEYCLOAK ON USERS(KEYCLOAK_ID);
CREATE INDEX IDX_USERS_EMAIL    ON USERS(EMAIL);
CREATE INDEX IDX_USERS_ROLE     ON USERS(ROLE_ID);

INSERT INTO ROLES (NAME, PERMISSIONS) VALUES ('Super Admin', '["*"]');
INSERT INTO ROLES (NAME, PERMISSIONS) VALUES ('Admin',       '["admin.*"]');
INSERT INTO ROLES (NAME, PERMISSIONS) VALUES ('Editor',      '["content.write","content.read","media.write","media.read"]');
INSERT INTO ROLES (NAME, PERMISSIONS) VALUES ('Author',      '["content.write","content.read","media.read"]');
INSERT INTO ROLES (NAME, PERMISSIONS) VALUES ('Viewer',      '["content.read"]');

COMMIT;
