-- BUILD ONLY: run npm run db:migrate when Oracle available

CREATE TABLE AUDIT_LOG (
  ID          RAW(16)       DEFAULT SYS_GUID() PRIMARY KEY,
  ACTOR_ID    RAW(16),
  ACTION      VARCHAR2(100) NOT NULL,
  ENTITY_TYPE VARCHAR2(100),
  ENTITY_ID   VARCHAR2(255),
  DIFF        CLOB          CHECK (DIFF IS JSON),
  PREV_HASH   VARCHAR2(64),
  HASH        VARCHAR2(64)  NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_AUDIT_ACTOR      ON AUDIT_LOG(ACTOR_ID);
CREATE INDEX IDX_AUDIT_ENTITY     ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_CREATED_AT ON AUDIT_LOG(CREATED_AT);
