-- BUILD ONLY: run npm run db:migrate when Oracle available

CREATE TABLE PAGES (
  ID           RAW(16)       DEFAULT SYS_GUID() PRIMARY KEY,
  TITLE        VARCHAR2(500) NOT NULL,
  SLUG         VARCHAR2(500) UNIQUE NOT NULL,
  STATUS       VARCHAR2(20)  DEFAULT 'draft' NOT NULL
                             CHECK (STATUS IN ('draft','review','approved','published','archived')),
  AUTHOR_ID    RAW(16)       REFERENCES USERS(ID),
  PUBLISHED_AT TIMESTAMP WITH TIME ZONE NULL,
  SCHEDULED_AT TIMESTAMP WITH TIME ZONE NULL,
  VIEW_COUNT   NUMBER        DEFAULT 0 NOT NULL,
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  DELETED_AT   TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IDX_PAGES_SLUG   ON PAGES(SLUG);
CREATE INDEX IDX_PAGES_STATUS ON PAGES(STATUS);
CREATE INDEX IDX_PAGES_AUTHOR ON PAGES(AUTHOR_ID);

CREATE TABLE BLOCKS (
  ID          RAW(16)       DEFAULT SYS_GUID() PRIMARY KEY,
  PAGE_ID     RAW(16)       NOT NULL REFERENCES PAGES(ID) ON DELETE CASCADE,
  BLOCK_TYPE  VARCHAR2(50)  NOT NULL,
  BLOCK_ORDER NUMBER        NOT NULL,
  CONTENT     CLOB          CHECK (CONTENT IS JSON),
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_BLOCKS_PAGE ON BLOCKS(PAGE_ID, BLOCK_ORDER);
