-- BUILD ONLY: run npm run db:migrate when Oracle available
CREATE TABLE REVISIONS (
  ID          RAW(16)                    DEFAULT SYS_GUID() PRIMARY KEY,
  PAGE_ID     RAW(16)                    NOT NULL REFERENCES PAGES(ID) ON DELETE CASCADE,
  TITLE       VARCHAR2(500)              NOT NULL,
  BLOCKS      CLOB                       CHECK (BLOCKS IS JSON),
  CREATED_BY  RAW(16)                    REFERENCES USERS(ID),
  CREATED_AT  TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_REVISIONS_PAGE ON REVISIONS (PAGE_ID, CREATED_AT DESC);
