-- BUILD ONLY: run npm run db:migrate when Oracle available
-- TS-3.1 Media Management tables

CREATE TABLE MEDIA (
  ID             RAW(16)          DEFAULT SYS_GUID() NOT NULL,
  FILENAME       VARCHAR2(500)    NOT NULL,
  MIME_TYPE      VARCHAR2(100),
  SIZE_BYTES     NUMBER,
  STORAGE_DRIVER VARCHAR2(20)     DEFAULT 'local',
  STORAGE_PATH   VARCHAR2(1000)   NOT NULL,
  UPLOADED_BY    RAW(16)          REFERENCES USERS(ID),
  CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETED_AT     TIMESTAMP WITH TIME ZONE,
  CONSTRAINT PK_MEDIA PRIMARY KEY (ID)
);

CREATE INDEX IDX_MEDIA_UPLOADED_BY ON MEDIA (UPLOADED_BY);
CREATE INDEX IDX_MEDIA_CREATED_AT  ON MEDIA (CREATED_AT DESC);
CREATE INDEX IDX_MEDIA_DELETED_AT  ON MEDIA (DELETED_AT);

CREATE TABLE MEDIA_VARIANTS (
  ID           RAW(16)        DEFAULT SYS_GUID() NOT NULL,
  MEDIA_ID     RAW(16)        NOT NULL REFERENCES MEDIA(ID) ON DELETE CASCADE,
  VARIANT      VARCHAR2(20)   NOT NULL,
  STORAGE_PATH VARCHAR2(1000) NOT NULL,
  WIDTH        NUMBER,
  HEIGHT       NUMBER,
  CONSTRAINT PK_MEDIA_VARIANTS PRIMARY KEY (ID),
  CONSTRAINT CK_MEDIA_VARIANT  CHECK (VARIANT IN ('thumbnail','small','medium','large')),
  CONSTRAINT UQ_MEDIA_VARIANT  UNIQUE (MEDIA_ID, VARIANT)
);

CREATE INDEX IDX_MEDIA_VARIANTS_MEDIA ON MEDIA_VARIANTS (MEDIA_ID);
