-- BUILD ONLY: run npm run db:migrate when Oracle available
CREATE TABLE THEMES (
  ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME       VARCHAR2(255)    NOT NULL,
  SLUG       VARCHAR2(100)    NOT NULL,
  PATH       VARCHAR2(1000)   NOT NULL,
  IS_ACTIVE  NUMBER(1)        DEFAULT 0 NOT NULL,
  SETTINGS   CLOB             DEFAULT '{}' CHECK (SETTINGS IS JSON),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT THEMES_SLUG_UQ UNIQUE (SLUG)
);

CREATE INDEX THEMES_ACTIVE_IDX ON THEMES (IS_ACTIVE);
