-- BUILD ONLY: run npm run db:migrate when Oracle available

CREATE TABLE DATA_SOURCES (
  ID              RAW(16)       DEFAULT SYS_GUID() PRIMARY KEY,
  NAME            VARCHAR2(255) NOT NULL,
  SOURCE_TYPE     VARCHAR2(20)  NOT NULL
                  CONSTRAINT CK_DS_TYPE CHECK (
                    SOURCE_TYPE IN ('oracle', 'postgresql', 'rest_api', 'csv')
                  ),
  CONNECTION_CONFIG CLOB        NOT NULL
                  CONSTRAINT CK_DS_CONFIG_JSON CHECK (CONNECTION_CONFIG IS JSON),
  CREATED_BY      RAW(16),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DATA_QUERIES (
  ID           RAW(16)  DEFAULT SYS_GUID() PRIMARY KEY,
  SOURCE_ID    RAW(16)  NOT NULL REFERENCES DATA_SOURCES(ID) ON DELETE CASCADE,
  QUERY_CONFIG CLOB     NOT NULL
               CONSTRAINT CK_DQ_CONFIG_JSON CHECK (QUERY_CONFIG IS JSON),
  CACHE_TTL    NUMBER   DEFAULT 300 NOT NULL,
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_DQ_SOURCE_ID ON DATA_QUERIES (SOURCE_ID);
