-- BUILD ONLY: run npm run db:migrate when Oracle available
-- TS-9.1: Plugin model

CREATE TABLE PLUGINS (
  ID              RAW(16)           DEFAULT SYS_GUID() PRIMARY KEY,
  NAME            VARCHAR2(255)     NOT NULL,
  VERSION         VARCHAR2(50)      NOT NULL,
  STATUS          VARCHAR2(20)      DEFAULT 'inactive'
                                    CHECK (STATUS IN ('inactive','active','error')),
  MANIFEST        CLOB              CHECK (MANIFEST IS JSON),
  INSTALLED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  ACTIVATED_AT    TIMESTAMP WITH TIME ZONE,
  CONSTRAINT UQ_PLUGINS_NAME UNIQUE (NAME)
);

CREATE TABLE PLUGIN_SETTINGS (
  ID          RAW(16)     DEFAULT SYS_GUID() PRIMARY KEY,
  PLUGIN_ID   RAW(16)     NOT NULL REFERENCES PLUGINS(ID) ON DELETE CASCADE,
  KEY         VARCHAR2(255) NOT NULL,
  VALUE       CLOB,
  CONSTRAINT UQ_PLUGIN_SETTINGS UNIQUE (PLUGIN_ID, KEY)
);

CREATE INDEX IDX_PLUGINS_STATUS   ON PLUGINS(STATUS);
CREATE INDEX IDX_PLUGIN_SETTINGS_PLUGIN ON PLUGIN_SETTINGS(PLUGIN_ID);
