-- BUILD ONLY: run npm run db:migrate when Oracle available
-- TS-10.5: Notifications table

CREATE TABLE NOTIFICATIONS (
  ID          RAW(16)                  DEFAULT SYS_GUID() PRIMARY KEY,
  USER_ID     RAW(16)                  REFERENCES USERS(ID) ON DELETE CASCADE,
  TYPE        VARCHAR2(50)             NOT NULL,
  TITLE       VARCHAR2(500)            NOT NULL,
  BODY        VARCHAR2(4000),
  ENTITY_ID   RAW(16),
  ENTITY_TYPE VARCHAR2(100),
  IS_READ     NUMBER(1)                DEFAULT 0 CHECK (IS_READ IN (0, 1)),
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_NOTIFICATIONS_USER      ON NOTIFICATIONS(USER_ID, IS_READ, CREATED_AT DESC);
CREATE INDEX IDX_NOTIFICATIONS_ENTITY    ON NOTIFICATIONS(ENTITY_TYPE, ENTITY_ID);
