-- BUILD ONLY: run npm run db:migrate when Oracle available

CREATE TABLE CATEGORIES (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME        VARCHAR2(255)                           NOT NULL,
  SLUG        VARCHAR2(255)                           NOT NULL,
  PARENT_ID   NUMBER                                  REFERENCES CATEGORIES(ID) ON DELETE SET NULL,
  SORT_ORDER  NUMBER DEFAULT 0                        NOT NULL,
  CONSTRAINT UQ_CATEGORIES_SLUG UNIQUE (SLUG)
);

CREATE TABLE TAGS (
  ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME  VARCHAR2(255) NOT NULL,
  SLUG  VARCHAR2(255) NOT NULL,
  CONSTRAINT UQ_TAGS_SLUG UNIQUE (SLUG)
);

CREATE TABLE PAGE_CATEGORIES (
  PAGE_ID      RAW(16)  NOT NULL REFERENCES PAGES(ID) ON DELETE CASCADE,
  CATEGORY_ID  NUMBER   NOT NULL REFERENCES CATEGORIES(ID) ON DELETE CASCADE,
  CONSTRAINT PK_PAGE_CATEGORIES PRIMARY KEY (PAGE_ID, CATEGORY_ID)
);

CREATE TABLE PAGE_TAGS (
  PAGE_ID  RAW(16)  NOT NULL REFERENCES PAGES(ID) ON DELETE CASCADE,
  TAG_ID   NUMBER   NOT NULL REFERENCES TAGS(ID) ON DELETE CASCADE,
  CONSTRAINT PK_PAGE_TAGS PRIMARY KEY (PAGE_ID, TAG_ID)
);

CREATE INDEX IDX_CATEGORIES_PARENT  ON CATEGORIES (PARENT_ID);
CREATE INDEX IDX_PAGE_CATEGORIES_PG ON PAGE_CATEGORIES (PAGE_ID);
CREATE INDEX IDX_PAGE_TAGS_PG       ON PAGE_TAGS (PAGE_ID);
