-- BUILD ONLY: run npm run db:migrate when Oracle available

-- VIEW_COUNT already exists on PAGES from 0003_content.sql (no ALTER needed)

CREATE TABLE PAGE_RATINGS (
  ID         RAW(16)      DEFAULT SYS_GUID() PRIMARY KEY,
  PAGE_ID    RAW(16)      NOT NULL REFERENCES PAGES(ID) ON DELETE CASCADE,
  HELPFUL    NUMBER(1)    NOT NULL CHECK (HELPFUL IN (0, 1)),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_PAGE_RATINGS_PAGE ON PAGE_RATINGS(PAGE_ID);
