-- Oracle XE init script — runs once on first container startup as SYSDBA
-- Creates application schema user and test schema user.
-- gvenzl/oracle-xe: APP_USER/APP_USER_PASSWORD env vars create the primary user
-- automatically; this script creates the secondary AURORA_TEST user.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'AURORA_TEST';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER AURORA_TEST IDENTIFIED BY aurora_test_dev
      DEFAULT TABLESPACE USERS
      TEMPORARY TABLESPACE TEMP
      QUOTA UNLIMITED ON USERS';

    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO AURORA_TEST';
    -- Oracle Text support
    EXECUTE IMMEDIATE 'GRANT CTXAPP TO AURORA_TEST';
    -- Oracle Advanced Queuing support
    EXECUTE IMMEDIATE 'GRANT AQ_ADMINISTRATOR_ROLE TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_AQ TO AURORA_TEST';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_AQADM TO AURORA_TEST';
  END IF;

  -- Ensure AURORA_CMS (created by APP_USER env) has the same grants
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'AURORA_CMS';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'GRANT CTXAPP TO AURORA_CMS';
    EXECUTE IMMEDIATE 'GRANT AQ_ADMINISTRATOR_ROLE TO AURORA_CMS';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_AQ TO AURORA_CMS';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_AQADM TO AURORA_CMS';
  END IF;
END;
/
