-- BUILD ONLY: run npm run db:migrate when Oracle available

CREATE OR REPLACE PACKAGE AURORA_CMS.SEARCH_PKG AS
    PROCEDURE SYNC_INDEX;
END SEARCH_PKG;
/

CREATE OR REPLACE PACKAGE BODY AURORA_CMS.SEARCH_PKG AS
    PROCEDURE SYNC_INDEX IS
    BEGIN
        CTX_DDL.SYNC_INDEX('CONTENT_SEARCH_IDX');
    END SYNC_INDEX;
END SEARCH_PKG;
/
